# feeder
feeder: feeders.feeder.Feeder
test_feeder_args:
  data_path: ./data/gsl_mediapipe/val_data_joint.npy
  label_path: ./data/gsl_mediapipe/val_label.pkl
  debug: False

# model
model: model.msg3d.Model
model_args:
  num_class: 321
  num_point: 75
  num_person: 1
  num_gcn_scales: 8
  num_g3d_scales: 8
  graph: graph.gsl_mediapipe.AdjMatrixGraph


# test
phase: test
device: 0
test_batch_size: 32
weights: ./pretrained-models/gsl-mediapipe-cross-joint.pt

work_dir: ./pretrain_eval/gsl_mediapipe
save_score: True
