# feeder
feeder: feeders.feeder.Feeder
test_feeder_args:
  data_path: ./data/gsl_openpose/val_data_bone.npy
  label_path: ./data/gsl_openpose/val_label.pkl
  debug: False

# model
model: model.msg3d.Model
model_args:
  num_class: 412 #312
  num_point: 67
  num_person: 1
  num_gcn_scales: 8
  num_g3d_scales: 8
  graph: graph.gsl_openpose.AdjMatrixGraph


# test
phase: test
device: 0
test_batch_size: 32
weights: ./pretrained_models/gsl_openpose_bone.pt

work_dir: ./eval/gsl_openpose/bone/
save_score: True
